name: serverless-guru-code

on:
  push:
    branches:
      - prod
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Serverless Framework
      run: npm install -g serverless 

    - name: Install dependencies
      run: npm install

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: deploy api to dev environment
      if: endsWith(github.ref, '/dev')
      run: sls deploy --stage dev
      
    - name: deploy api to prod environment
      if: endsWith(github.ref, '/prod')
      run: sls deploy --stage prod